modLoader="javafml" #mandatory
loaderVersion="${forge_version_range}" #mandatory
license="${license}"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
# A display name for the mod
displayName="${description}" #mandatory
# logoFile="siegemachines.png" #optional // TODO Logo
credits="${credits}"
authors="${mod_author}" #optional
description='''${description}'''
[[dependencies.siegemachines]]
modId = "minecraft"
versionRange = "[${minecraft_min_version},${minecraft_max_version})"
mandatory = true
side = "BOTH"
ordering = "NONE"

[[dependencies.siege_machine_compat]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.siege_machine_compat]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.siege_machine_compat]]
modId="recruits"
mandatory=true
versionRange=">=${villager_recruits_version}"
ordering="AFTER"
side="BOTH"

[[dependencies.siege_machine_compat]]
modId="siegemachines"
mandatory=true
versionRange=">=${siege_machines_version}"
ordering="AFTER"
side="BOTH"
